image: gitpod/workspace-full

tasks:
  - init: |
      git remote set-url origin https://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@github.com/douglasviniii/aginotas-backend.git
      npm install
  - command: npm start